"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Database } from "@/types/database";
type Option={id:string;name:string};
const fieldClass="w-full rounded-lg border border-[#1e2a35] bg-[#0d141b] px-2.5 py-2 text-xs text-[#e9f0f6] outline-none placeholder:text-[#607080] transition focus:border-[#2dd4bf]/70 focus:ring-2 focus:ring-[#2dd4bf]/10";
const labelClass="text-[10px] font-bold uppercase tracking-[.55px] text-[#8b9aa8]";
export function NewProjectForm({orgId,userId,departments,brands}:{orgId:string;userId:string;departments:Option[];brands:Option[]}){
 const router=useRouter();const supabase=createClient();const[open,setOpen]=useState(false);const[name,setName]=useState("");const[description,setDescription]=useState("");const[departmentId,setDepartmentId]=useState("");const[brandId,setBrandId]=useState("");const[dueDate,setDueDate]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 function reset(){setName("");setDescription("");setDepartmentId("");setBrandId("");setDueDate("");setError(null)} function closeFloatingForm(){if(busy)return;reset();setOpen(false)}
 async function handleSubmit(e:React.FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);setError(null);const payload:Database["public"]["Tables"]["projects"]["Insert"]={org_id:orgId,name:name.trim(),description:description.trim()||null,department_id:departmentId||null,brand_id:brandId||null,due_date:dueDate||null,status:"active",owner_id:userId,created_by:userId};const{error:insertError}=await supabase.from("projects").insert(payload as never);setBusy(false);if(insertError){setError(insertError.message);return}reset();setOpen(false);router.refresh()}
 return <div className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} className="rounded-lg border border-[#1e2a35] bg-[#0d141b] px-3 py-1.5 text-xs font-bold text-[#b8c4cf] transition hover:border-[#2dd4bf]/35 hover:text-[#e9f0f6]">+ New project</button>{open&&<form onSubmit={handleSubmit} className="absolute right-0 top-[calc(100%+9px)] z-[80] w-[min(480px,calc(100vw-28px))] rounded-2xl border border-[#1e2a35] bg-[#111820] p-4 shadow-[0_22px_60px_rgba(0,0,0,.55)]">
 <div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-[9px] font-extrabold uppercase tracking-[1px] text-[#2dd4bf]">Task board</p><div className="flex items-center gap-2"><h2 className="text-base font-extrabold text-[#e9f0f6]">Create new project</h2><span className="group relative inline-flex"><button type="button" aria-label="About new projects" className="grid h-[18px] w-[18px] place-items-center rounded-full border border-[#263744] bg-[#0d141b] text-[10px] font-bold text-[#8b9aa8] transition hover:border-[#2dd4bf]/50 hover:text-[#2dd4bf] focus-visible:border-[#2dd4bf]/50 focus-visible:text-[#2dd4bf]">?</button><span role="tooltip" className="pointer-events-none absolute left-1/2 top-[calc(100%+8px)] z-[100] w-max max-w-[240px] -translate-x-1/2 rounded-lg border border-[#263744] bg-[#0b1117] px-2.5 py-2 text-[11px] font-normal normal-case tracking-normal text-[#b8c4cf] opacity-0 shadow-[0_12px_32px_rgba(0,0,0,.5)] transition-opacity group-hover:opacity-100 group-focus-within:opacity-100">Group related tasks and set a delivery target.</span></span></div></div><button type="button" onClick={closeFloatingForm} className="grid h-7 w-7 place-items-center rounded-full border border-[#1e2a35] bg-[#0d141b] text-base text-[#8b9aa8]">×</button></div>
 <div className="grid gap-2.5"><label className={labelClass}>Project name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Name this project" className={`${fieldClass} mt-1 normal-case tracking-normal`}/></label><label className={labelClass}>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add context or notes…" rows={2} className={`${fieldClass} mt-1 resize-none normal-case tracking-normal`}/></label><div className="grid grid-cols-3 gap-2"><label className={labelClass}>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}><option value="">None</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className={labelClass}>Brand<select value={brandId} onChange={e=>setBrandId(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}><option value="">None</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className={labelClass}>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}/></label></div></div>
 {error&&<p className="mt-3 rounded-lg border border-[#f26d6d]/25 bg-[#f26d6d]/10 px-2.5 py-1.5 text-[10px] text-[#fca5a5]">{error}</p>}<div className="mt-4 flex justify-end gap-2 border-t border-[#1e2a35] pt-3"><button type="button" onClick={closeFloatingForm} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#8b9aa8]">Cancel</button><button type="submit" disabled={busy||!name.trim()} className="rounded-lg bg-[#2dd4bf] px-4 py-2 text-xs font-extrabold text-[#07110f] disabled:opacity-40">{busy?"Creating…":"Create project"}</button></div>
 </form>}</div>;
}
