"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { TASK_PRIORITIES, TASK_PRIORITY_LABELS, TASK_STATUSES, TASK_STATUS_LABELS } from "@/lib/tasks/display";
import { TagUsersField } from "@/components/tasks/TagUsersField";
import type { Database, TaskPriority, TaskStatus } from "@/types/database";

type Option = { id: string; name: string };
const fieldClass = "w-full rounded-lg border border-[#1e2a35] bg-[#0d141b] px-2.5 py-2 text-xs text-[#e9f0f6] outline-none placeholder:text-[#607080] transition focus:border-[#2dd4bf]/70 focus:ring-2 focus:ring-[#2dd4bf]/10";
const labelClass = "text-[10px] font-bold uppercase tracking-[.55px] text-[#8b9aa8]";

export function NewTaskForm({ orgId, userId, projects, users, brands, canTag = false }: { orgId: string; userId: string; projects: Option[]; users: Option[]; brands: Option[]; canTag?: boolean; }) {
  const router = useRouter(); const supabase = createClient();
  const [open,setOpen]=useState(false); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [priority,setPriority]=useState<TaskPriority>("medium"); const [status,setStatus]=useState<TaskStatus>("todo"); const [dueDate,setDueDate]=useState(""); const [projectId,setProjectId]=useState(""); const [assigneeId,setAssigneeId]=useState(""); const [brandId,setBrandId]=useState(""); const [tagUserIds,setTagUserIds]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [aiBrief,setAiBrief]=useState(""); const [aiBusy,setAiBusy]=useState(false); const [aiNote,setAiNote]=useState<string|null>(null); const [aiError,setAiError]=useState<string|null>(null);
  function reset(){setTitle("");setDescription("");setPriority("medium");setStatus("todo");setDueDate("");setProjectId("");setAssigneeId("");setBrandId("");setAiBrief("");setAiNote(null);setAiError(null);setTagUserIds([]);setError(null)}
  function closeFloatingForm(){if(busy)return;reset();setOpen(false)}
  async function handleDraft(){const brief=aiBrief.trim();if(!brief||aiBusy)return;setAiBusy(true);setAiError(null);setAiNote(null);try{const res=await fetch("/api/tasks/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brief})});if(!res.ok){setAiError("AI draft unavailable — fill the form in manually.");return}const data=(await res.json()) as {draft?:{title?:string;description?:string;priority?:TaskPriority;assigneeHint?:string;departmentHint?:string}};const draft=data.draft;if(!draft){setAiError("AI draft unavailable — fill the form in manually.");return}if(draft.title)setTitle(draft.title);if(draft.description)setDescription(draft.description);if(draft.priority&&(TASK_PRIORITIES as string[]).includes(draft.priority))setPriority(draft.priority);const hint=(draft.assigneeHint??"").trim().toLowerCase();let matchedName="";if(hint){const exact=users.find(u=>u.name.trim().toLowerCase()===hint);const loose=exact??users.find(u=>u.name.trim().toLowerCase().includes(hint)||hint.includes(u.name.trim().toLowerCase()));if(loose){setAssigneeId(loose.id);matchedName=loose.name}}const bits=["Fields pre-filled from your brief — review before saving."];if(draft.departmentHint)bits.push(`Suggested department: ${draft.departmentHint}.`);if(draft.assigneeHint&&!matchedName)bits.push(`Suggested assignee: ${draft.assigneeHint} — pick manually.`);else if(matchedName)bits.push(`Assignee set to ${matchedName}.`);setAiNote(bits.join(" "))}catch{setAiError("AI draft unavailable — fill the form in manually.")}finally{setAiBusy(false)}}
  async function handleSubmit(e:React.FormEvent){e.preventDefault();if(!title.trim())return;if(!(TASK_PRIORITIES as string[]).includes(priority)){setError(`"${priority}" is not a valid priority.`);return}if(!(TASK_STATUSES as string[]).includes(status)){setError(`"${status}" is not a valid status.`);return}setBusy(true);setError(null);const payload:Database["public"]["Tables"]["tasks"]["Insert"]={org_id:orgId,title:title.trim(),description:description.trim()||null,priority,status,due_date:dueDate||null,project_id:projectId||null,assignee_id:assigneeId||null,brand_id:brandId||null,created_by:userId};const{data:inserted,error:insertError}=await supabase.from("tasks").insert(payload as never).select("id").single();if(insertError){setBusy(false);setError(insertError.message);return}const newId=(inserted as {id?:string}|null)?.id;if(canTag&&newId&&tagUserIds.length>0){try{await fetch("/api/tasks/snap-tag",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:newId,userIds:tagUserIds})})}catch{}}setBusy(false);reset();setOpen(false);router.refresh()}
  return <div className="relative">
    <button type="button" onClick={()=>setOpen(v=>!v)} className="rounded-lg border border-[#2dd4bf]/25 bg-[#2dd4bf] px-3 py-1.5 text-xs font-extrabold text-[#07110f] shadow-[0_6px_16px_rgba(45,212,191,.1)] transition hover:bg-[#5eead4]">+ New task</button>
    {open&&<form onSubmit={handleSubmit} className="absolute right-0 top-[calc(100%+9px)] z-[80] max-h-[calc(100vh-120px)] w-[min(590px,calc(100vw-28px))] overflow-y-auto rounded-2xl border border-[#1e2a35] bg-[#111820] p-4 shadow-[0_22px_60px_rgba(0,0,0,.55)]">
      <div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-[9px] font-extrabold uppercase tracking-[1px] text-[#2dd4bf]">Task board</p><h2 className="text-base font-extrabold text-[#e9f0f6]">Create new task</h2><p className="mt-0.5 text-[11px] text-[#8b9aa8]">Assign an owner and set the delivery target.</p></div><button type="button" onClick={closeFloatingForm} className="grid h-7 w-7 place-items-center rounded-full border border-[#1e2a35] bg-[#0d141b] text-base text-[#8b9aa8]">×</button></div>
      <div className="mb-3 rounded-xl border border-[#2dd4bf]/20 bg-[#0d141b] p-2.5"><div className="mb-1.5 flex gap-2 text-[10px]"><span className="font-bold text-[#2dd4bf]">✦ AI draft</span><span className="text-[#607080]">Optional</span></div><div className="flex gap-2"><input value={aiBrief} onChange={e=>setAiBrief(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void handleDraft()}}} placeholder="Describe the task in one line…" className={fieldClass}/><button type="button" onClick={()=>void handleDraft()} disabled={aiBusy||!aiBrief.trim()} className="shrink-0 rounded-lg border border-[#2dd4bf]/35 bg-[#2dd4bf]/10 px-3 py-2 text-[10px] font-bold text-[#5eead4] disabled:opacity-40">{aiBusy?"Drafting…":"Draft with AI"}</button></div>{aiNote&&<p className="mt-1.5 text-[10px] text-[#5eead4]">{aiNote}</p>}{aiError&&<p className="mt-1.5 text-[10px] text-[#8b9aa8]">{aiError}</p>}</div>
      <div className="grid gap-2.5"><label className={labelClass}>Task title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs to get done?" className={`${fieldClass} mt-1 normal-case tracking-normal`}/></label><label className={labelClass}>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add context or notes…" rows={2} className={`${fieldClass} mt-1 resize-none normal-case tracking-normal`}/></label>
      <div className="grid grid-cols-3 gap-2"><label className={labelClass}>Priority<select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)} className={`${fieldClass} mt-1 normal-case tracking-normal`}>{TASK_PRIORITIES.map(p=><option key={p} value={p}>{TASK_PRIORITY_LABELS[p]}</option>)}</select></label><label className={labelClass}>Status<select value={status} onChange={e=>setStatus(e.target.value as TaskStatus)} className={`${fieldClass} mt-1 normal-case tracking-normal`}>{TASK_STATUSES.map(s=><option key={s} value={s}>{TASK_STATUS_LABELS[s]}</option>)}</select></label><label className={labelClass}>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}/></label></div>
      <div className="grid grid-cols-3 gap-2"><label className={labelClass}>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}><option value="">None</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className={labelClass}>Assignee<select value={assigneeId} onChange={e=>setAssigneeId(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className={labelClass}>Brand<select value={brandId} onChange={e=>setBrandId(e.target.value)} className={`${fieldClass} mt-1 normal-case tracking-normal`}><option value="">None</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>{canTag&&<div className="rounded-lg border border-[#1e2a35] bg-[#0d141b] p-2"><TagUsersField users={users.filter(u=>u.id!==userId)} value={tagUserIds} onChange={setTagUserIds} label="Tag teammates (Snap-Tag)" hint="Tagged teammates get notified separately."/></div>}</div>
      {error&&<p className="mt-3 rounded-lg border border-[#f26d6d]/25 bg-[#f26d6d]/10 px-2.5 py-1.5 text-[10px] text-[#fca5a5]">{error}</p>}<div className="mt-4 flex justify-end gap-2 border-t border-[#1e2a35] pt-3"><button type="button" onClick={closeFloatingForm} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#8b9aa8]">Cancel</button><button type="submit" disabled={busy||!title.trim()} className="rounded-lg bg-[#2dd4bf] px-4 py-2 text-xs font-extrabold text-[#07110f] disabled:opacity-40">{busy?"Adding…":"Create task"}</button></div>
    </form>}
  </div>;
}
