import Link from "next/link";
import { revalidatePath } from "next/cache";
import { AppShell } from "@/components/layout/AppShell";
import { NewTaskForm } from "@/components/tasks/NewTaskForm";
import { NewProjectForm } from "@/components/tasks/NewProjectForm";
import { PageHeader, SectionCard, TableShell, rowClass, HelpHint } from "@/components/ui";
import { requireProfile, requireRole } from "@/lib/auth/session";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { TASK_STATUSES, TASK_STATUS_LABELS, TASK_PRIORITIES, TASK_PRIORITY_LABELS, PROJECT_STATUSES, statusPillClasses, priorityClasses, formatDate } from "@/lib/tasks/display";
import type { TaskStatus, TaskPriority, ProjectStatus } from "@/types/database";
import { TemplateCsvButton } from "./TemplateCsvButton";
import { ImportTasksControl, type ImportTasksState } from "./ImportTasksControl";
import { ImportProjectsControl, type ImportProjectsState } from "./ImportProjectsControl";
import { RowActions } from "@/components/archive/RowActions";
import { ArchivedToggle } from "@/components/archive/ArchivedToggle";
import { rowActionProps } from "@/lib/archive/config";

type DbShim = { from: (t: string) => { insert: (v: Record<string, unknown>) => Promise<unknown> } };
function parseCsvLine(line: string): string[] { const out:string[]=[]; let cur="",inQuotes=false; for(let i=0;i<line.length;i++){const ch=line[i]; if(inQuotes){if(ch==='"'){if(line[i+1]==='"'){cur+='"';i++;}else inQuotes=false;}else cur+=ch;}else if(ch==='"')inQuotes=true;else if(ch===","){out.push(cur);cur="";}else cur+=ch;} out.push(cur);return out; }
function toDateOrNull(v:string):string|null { const t=v.trim(); return /^\d{4}-\d{2}-\d{2}$/.test(t)?t:null; }
async function csvTextFrom(formData:FormData):Promise<string>{const file=formData.get("file");if(file&&typeof file!=="string"&&file.size>0)return file.text();return String(formData.get("csv")??"");}

async function importTasks(_prev:ImportTasksState,formData:FormData):Promise<ImportTasksState>{"use server";const profile=(await requireRole(["ceo","coo","department_head"])) as unknown as {id:string;org_id:string};const text=await csvTextFrom(formData);const skipped:string[]=[];if(!text.trim())return{imported:0,skipped};const supabase=createServerSupabaseClient();const [usersRes,brandsRes,projectsRes,deptsRes]=await Promise.all([supabase.from("users").select("id, email").eq("org_id",profile.org_id),supabase.from("brands").select("id, name").eq("org_id",profile.org_id),supabase.from("projects").select("id, name").eq("org_id",profile.org_id),supabase.from("departments").select("id, name").eq("org_id",profile.org_id)]);const userByEmail=new Map(((usersRes.data??[]) as unknown as {id:string;email:string|null}[]).filter(u=>u.email).map(u=>[String(u.email).trim().toLowerCase(),u.id]));const brandByName=new Map(((brandsRes.data??[]) as unknown as {id:string;name:string}[]).map(b=>[b.name.trim().toLowerCase(),b.id]));const projectByName=new Map(((projectsRes.data??[]) as unknown as {id:string;name:string}[]).map(p=>[p.name.trim().toLowerCase(),p.id]));const deptByName=new Map(((deptsRes.data??[]) as unknown as {id:string;name:string}[]).map(d=>[d.name.trim().toLowerCase(),d.id]));const rows:Record<string,unknown>[]=[];for(const raw of text.split(/\r?\n/)){if(!raw.trim())continue;const cols=parseCsvLine(raw);const title=(cols[0]??"").trim();if(title.toLowerCase()==="title")continue;const description=(cols[1]??"").trim(),assigneeEmail=(cols[2]??"").trim(),brand=(cols[3]??"").trim(),project=(cols[4]??"").trim(),priorityRaw=(cols[5]??"").trim().toLowerCase(),statusRaw=(cols[6]??"").trim().toLowerCase(),dueDate=(cols[7]??"").trim(),department=(cols[8]??"").trim();if(!title){skipped.push("missing title (blank row)");continue;}let assignee_id:string|null=null;if(assigneeEmail){const matched=userByEmail.get(assigneeEmail.toLowerCase());if(!matched){skipped.push(`unknown assignee ${assigneeEmail} (${title})`);continue;}assignee_id=matched;}const brand_id=brand?brandByName.get(brand.toLowerCase())??null:null,project_id=project?projectByName.get(project.toLowerCase())??null:null;if(department)deptByName.get(department.toLowerCase());const priority:TaskPriority=(TASK_PRIORITIES as string[]).includes(priorityRaw)?priorityRaw as TaskPriority:"medium";const status:TaskStatus=(TASK_STATUSES as string[]).includes(statusRaw)?statusRaw as TaskStatus:"todo";rows.push({org_id:profile.org_id,created_by:profile.id,title,description:description||null,assignee_id,brand_id,project_id,priority,status,due_date:toDateOrNull(dueDate)});}const db=supabase as unknown as DbShim;for(const row of rows)await db.from("tasks").insert(row);revalidatePath("/tasks");return{imported:rows.length,skipped};}

async function importProjects(_prev:ImportProjectsState,formData:FormData):Promise<ImportProjectsState>{"use server";const profile=(await requireRole(["ceo","coo","department_head"])) as unknown as {id:string;org_id:string};const text=await csvTextFrom(formData);const skipped:string[]=[];if(!text.trim())return{imported:0,skipped};const supabase=createServerSupabaseClient();const [usersRes,deptsRes]=await Promise.all([supabase.from("users").select("id, email").eq("org_id",profile.org_id),supabase.from("departments").select("id, name").eq("org_id",profile.org_id)]);const userByEmail=new Map(((usersRes.data??[]) as unknown as {id:string;email:string|null}[]).filter(u=>u.email).map(u=>[String(u.email).trim().toLowerCase(),u.id]));const deptByName=new Map(((deptsRes.data??[]) as unknown as {id:string;name:string}[]).map(d=>[d.name.trim().toLowerCase(),d.id]));const rows:Record<string,unknown>[]=[];for(const raw of text.split(/\r?\n/)){if(!raw.trim())continue;const cols=parseCsvLine(raw);const name=(cols[0]??"").trim();if(name.toLowerCase()==="name")continue;const description=(cols[1]??"").trim(),department=(cols[2]??"").trim(),ownerEmail=(cols[3]??"").trim(),statusRaw=(cols[4]??"").trim().toLowerCase(),dueDate=(cols[6]??"").trim();if(!name){skipped.push("missing name (blank row)");continue;}let owner_id:string|null=null;if(ownerEmail){const matched=userByEmail.get(ownerEmail.toLowerCase());if(!matched){skipped.push(`unknown owner ${ownerEmail} (${name})`);continue;}owner_id=matched;}const department_id=department?deptByName.get(department.toLowerCase())??null:null;const status:ProjectStatus=(PROJECT_STATUSES as string[]).includes(statusRaw)?statusRaw as ProjectStatus:"active";rows.push({org_id:profile.org_id,created_by:profile.id,name,description:description||null,department_id,owner_id,status,due_date:toDateOrNull(dueDate)});}const db=supabase as unknown as DbShim;for(const row of rows)await db.from("projects").insert(row);revalidatePath("/tasks");return{imported:rows.length,skipped};}

type TaskLite={id:string;title:string;status:TaskStatus;priority:TaskPriority;due_date:string|null;project_id:string|null;assignee_id:string|null;brand_id:string|null;parent_task_id:string|null;archived_at:string|null};type ProjectLite={id:string;name:string;status:string};type NamedRow={id:string;name:string};type UserRow={id:string;full_name:string};

export default async function TasksPage({searchParams}:{searchParams?:{archived?:string}}){const archived=searchParams?.archived==="1";const profile=await requireProfile();const canImport=profile.role==="ceo"||profile.role==="coo"||profile.role==="department_head";const supabase=createServerSupabaseClient();const tasksQ=supabase.from("tasks").select("id, title, status, priority, due_date, project_id, assignee_id, brand_id, parent_task_id, archived_at").order("created_at",{ascending:false});const [tasksRes,projectsRes,usersRes,brandsRes,deptsRes]=await Promise.all([archived?tasksQ.not("archived_at","is",null):tasksQ.is("archived_at",null),supabase.from("projects").select("id, name, status").order("created_at",{ascending:false}),supabase.from("users").select("id, full_name").order("full_name"),supabase.from("brands").select("id, name").order("name"),supabase.from("departments").select("id, name").order("name")]);const tasks=(tasksRes.data??[]) as unknown as TaskLite[],projects=(projectsRes.data??[]) as unknown as ProjectLite[],users=(usersRes.data??[]) as unknown as UserRow[],brands=(brandsRes.data??[]) as unknown as NamedRow[],departments=(deptsRes.data??[]) as unknown as NamedRow[];const userName=new Map(users.map(u=>[u.id,u.full_name])),projectName=new Map(projects.map(p=>[p.id,p.name])),brandName=new Map(brands.map(b=>[b.id,b.name])),userOptions=users.map(u=>({id:u.id,name:u.full_name}));const topLevel=tasks.filter(t=>!t.parent_task_id),openCount=topLevel.filter(t=>t.status!=="done"&&t.status!=="cancelled").length;
return <AppShell breadcrumb={["Mthryve OS","Tasks"]} profile={profile}>
<div className="h-[calc(100vh-112px)] overflow-hidden">
<PageHeader title={<>Tasks <HelpHint id="work.tasks" /></>} subtitle={<>{openCount} open · {topLevel.length} total · {projects.length} project{projects.length===1?"":"s"}</>} action={<div className="flex items-center gap-2"><NewProjectForm orgId={profile.org_id} userId={profile.id} departments={departments} brands={brands}/><NewTaskForm orgId={profile.org_id} userId={profile.id} projects={projects.map(p=>({id:p.id,name:p.name}))} users={userOptions} brands={brands} canTag={canImport}/></div>}/>
<div className="grid h-[430px] min-h-0 items-stretch gap-4 xl:grid-cols-3">
{canImport&&<SectionCard className="h-full min-h-0 min-w-0 overflow-hidden !p-3" title="Import Tasks (CSV)" action={<TemplateCsvButton headers={["title","description","assignee_email","brand","project","priority","status","due_date","department"]} example={["Launch Q3 campaign","Kickoff and asset prep","jane@example.com","Acme","Summer Launch","high","todo","2026-08-01","Marketing"]} filename="tasks_import_template.csv" label="Download template"/>}><ImportTasksControl action={importTasks}/></SectionCard>}
{canImport&&<SectionCard className="h-full min-h-0 min-w-0 overflow-hidden !p-3" title="Import Projects (CSV)" action={<TemplateCsvButton headers={["name","description","department","owner_email","status","start_date","due_date"]} example={["Summer Launch","Cross-brand summer push","Marketing","jane@example.com","active","2026-06-01","2026-08-31"]} filename="projects_import_template.csv" label="Download template"/>}><ImportProjectsControl action={importProjects}/></SectionCard>}
<section className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-2xl border border-charcoal-700 bg-charcoal-900 p-3 shadow-[inset_0_1px_0_rgba(255,255,255,.025)]"><div className="mb-3 flex shrink-0 items-center justify-between gap-3"><h2 className="text-sm font-semibold text-ink">Tasks</h2><ArchivedToggle basePath="/tasks" archived={archived}/></div>{topLevel.length===0?<div className="min-h-0 flex-1 rounded-xl border border-charcoal-700 bg-charcoal-950/45 p-4 text-sm text-ink-muted">{archived?"No archived tasks.":"No tasks yet. Create your first one with “New task”."}</div>:<div className="min-h-0 min-w-0 flex-1 overflow-auto"><TableShell columns={["Task","Project","Assignee","Priority","Due","Status","Manage"]}>{topLevel.map(t=><tr key={t.id} className={rowClass}><td className="px-4 py-2.5"><Link href={`/tasks/${t.id}`} className="text-ink hover:text-teal-400">{t.title}</Link>{t.brand_id&&brandName.get(t.brand_id)&&<span className="ml-2 rounded bg-charcoal-800 px-1.5 py-0.5 font-mono text-[10px] text-ink-muted">{brandName.get(t.brand_id)}</span>}</td><td className="px-4 py-2.5 text-ink-muted">{t.project_id?projectName.get(t.project_id)??"—":"—"}</td><td className="px-4 py-2.5 text-ink-muted">{t.assignee_id?userName.get(t.assignee_id)??"—":"Unassigned"}</td><td className={`px-4 py-2.5 font-medium ${priorityClasses(t.priority)}`}>{TASK_PRIORITY_LABELS[t.priority]}</td><td className="px-4 py-2.5 font-mono text-xs text-ink-muted">{formatDate(t.due_date)}</td><td className="px-4 py-2.5"><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${statusPillClasses(t.status)}`}>{TASK_STATUS_LABELS[t.status]}</span></td><td className="px-4 py-2.5"><RowActions {...rowActionProps("tasks",t as unknown as Record<string,unknown>,profile)}/></td></tr>)}</TableShell></div>}</section>
</div></div></AppShell>;
}
