"use client";

// MetricBriefToggle — the "✦ AI Brief" affordance under every Mission Control KPI
// and chart. Collapsed by default; expands to the four-line brief:
//   WHAT / WHY / HOW / POTENTIAL IMPACT
// WHAT and HOW are deterministic (derived from the real metric); WHY and
// POTENTIAL IMPACT are AI-generated and grounded in the same figures. The label
// colours encode the source — teal for the derived lines, violet for the AI
// lines — so it's always clear which came from the model. All content is passed
// in as props (server-rendered); this component only owns expand/collapse.

import { useEffect, useState } from "react";
import { useAiBriefs } from "./AiBriefsProvider";
import type { MetricBrief } from "@/lib/briefings/metric-briefs";

function Line({
  label,
  text,
  source,
}: {
  label: string;
  text: string;
  source: "derived" | "ai";
}) {
  return (
    <div>
      <dt
        className={`font-mono text-[9px] uppercase tracking-wider ${
          source === "ai" ? "text-violet-300/90" : "text-teal-300/80"
        }`}
      >
        {label}
      </dt>
      <dd className="mt-0.5 text-xs leading-relaxed text-ink-muted">{text}</dd>
    </div>
  );
}

export function MetricBriefToggle({ brief }: { brief: MetricBrief }) {
  const ctx = useAiBriefs();
  const [open, setOpen] = useState(false);

  // React to the header's "Expand all / Collapse all" broadcast.
  useEffect(() => {
    if (ctx?.pulse) setOpen(ctx.pulse.open);
    // Only the monotonic seq should retrigger this — not identity of `ctx`.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx?.pulse?.seq]);

  return (
    <div className="mt-3 border-t border-charcoal-800 pt-2">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-2 font-mono text-[10px] uppercase tracking-wider text-violet-300 transition-colors hover:text-violet-200"
      >
        <span className="flex items-center gap-1.5">
          <span aria-hidden>✦</span> AI Brief
        </span>
        <span aria-hidden className="text-ink-dim">
          {open ? "–" : "+"}
        </span>
      </button>

      {open && (
        <div className="mt-2 space-y-2">
          <dl className="space-y-2">
            <Line label="What" text={brief.what} source="derived" />
            <Line label="Why" text={brief.why} source="ai" />
            <Line label="How" text={brief.how} source="derived" />
            <Line label="Potential Impact" text={brief.impact} source="ai" />
          </dl>
          <p className="font-mono text-[9px] leading-relaxed text-ink-dim">
            {brief.grounded
              ? "✦ Why & Potential Impact generated by AI, grounded in the figures above · What & How derived from live data."
              : "What & How are derived from live data · Why & Potential Impact reflect the data honestly when the AI rationale isn't available."}
          </p>
        </div>
      )}
    </div>
  );
}
