"use client";

import { useState } from "react";

// CampaignBrief — the human-approved DRAFT flow. It reuses the existing
// content_generations generator (POST /api/content-studio/generate) with the
// new template_key 'campaign_brief'; the API writes the ledger row and returns
// the draft. Nothing auto-publishes: the planner reads it, can edit it, copy
// it, and optionally save it onto the campaign's notes via the passed server
// action. The brand context is composed server-side into `inputs`.

type Props = {
  campaignId: string;
  inputs: Record<string, string>;
  hasBrandContext: boolean;
  saveAction: (formData: FormData) => void | Promise<void>;
};

export function CampaignBrief({ campaignId, inputs, hasBrandContext, saveAction }: Props) {
  const [draft, setDraft] = useState("");
  const [model, setModel] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  async function generate() {
    setLoading(true);
    setError("");
    setCopied(false);
    try {
      const res = await fetch("/api/content-studio/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ templateKey: "campaign_brief", inputs }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      setDraft(data.output);
      setModel(data.model);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-semibold text-ink">Campaign brief</h3>
          <span className="rounded-full border border-violet-500/40 bg-violet-500/10 px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-violet-300">
            AI draft · human-approved
          </span>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="rounded-md bg-teal-500 px-3 py-1.5 text-xs font-semibold text-charcoal-950 hover:bg-teal-400 disabled:opacity-60"
        >
          {loading ? "Generating…" : draft ? "Regenerate" : "Generate campaign brief"}
        </button>
      </div>

      {!hasBrandContext && (
        <p className="text-xs text-amber-300/80">
          No account briefing or platform metrics are on file for this brand — the brief will be written from the
          campaign fields alone and will note its lower confidence rather than inventing a brand situation.
        </p>
      )}

      {error && <p className="text-xs text-red-400">{error}</p>}

      {!draft && !loading ? (
        <p className="text-sm text-ink-muted">
          Generate a grounded draft — objective, core angle, hook direction, target audience, primary CTA, and 2–3
          success KPIs — from this campaign and the brand&rsquo;s real situation.
        </p>
      ) : null}

      {draft ? (
        <form action={saveAction} className="space-y-2">
          <input type="hidden" name="campaign_id" value={campaignId} />
          <textarea
            name="draft"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            className="min-h-[240px] w-full rounded-md border border-charcoal-700 bg-charcoal-950 p-3 font-sans text-sm leading-relaxed text-ink"
          />
          <div className="flex flex-wrap items-center justify-between gap-2">
            {model ? (
              <span className="font-mono text-[10px] uppercase tracking-wider text-ink-muted">
                generated by {model} · saved as a content_generations row
              </span>
            ) : (
              <span />
            )}
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(draft);
                  setCopied(true);
                }}
                className="rounded-md border border-charcoal-700 px-3 py-1.5 text-xs text-ink-muted hover:bg-charcoal-800 hover:text-ink"
              >
                {copied ? "Copied ✓" : "Copy"}
              </button>
              <button
                type="submit"
                className="rounded-md bg-charcoal-800 px-3 py-1.5 text-xs font-semibold text-teal-300 hover:bg-charcoal-700"
              >
                Save to campaign notes
              </button>
            </div>
          </div>
        </form>
      ) : null}
    </div>
  );
}
