"use client";

export type TonyVisualState = "idle" | "listening" | "thinking" | "speaking";
export type OrbitApi = { setState:(s:TonyVisualState)=>void; zoom:(dir:number)=>void; reset:()=>void; destroy:()=>void };

const NODES = [
  ["Commerce","MERCHANT",0x3ecf8e,"terran",.36,0],["Finance","LEDGER",0x3ecf8e,"icegiant",.42,0],
  ["Creative","VESPER",0xf5b942,"jovian",.54,0],["Affiliate","SCOUT",0xa78bfa,"lava",.29,0],
  ["Trend · CSI","ORACLE",0xf5b942,"martian",.31,0],["Customer Care","CARE",0x2dd4bf,"ocean",.34,0],
  ["Live Selling","ANCHOR",0xf472b6,"venusian",.32,0],["Warehouse","LOGI",0x5aa9e6,"mercurial",.26,0],
  ["Reporting","HERALD",0x5aa9e6,"europan",.28,0],["Leads","PROSPECTOR",0x5aa9e6,"canyon",.30,0],
  ["Governance","SENTINEL",0xf5b942,"saturnian",.48,1],["Memory","RECALL",0xa78bfa,"carbon",.25,0],
  ["Knowledge","RAG · 538",0xa78bfa,"uranian",.44,1],["Calendar","NOTETAKER",0x5aa9e6,"hazy",.33,0],
] as const;

const DESC:Record<string,string> = {
  Commerce:"Merchant — shop health, GMV and sync. Proposes campaigns; you approve the spend.",
  Finance:"Ledger — settlement vs GMV, margin and cash. Leadership-gated, always.",
  Creative:"Vesper — 60-slot content matrix + live auto-clips. Drafts, never publishes alone.",
  Affiliate:"Scout — sources and tiers PH creators, matches them to under-activated brands.",
  "Trend · CSI":"Oracle — competitors, trends, market moves. Every finding cites a source.",
  "Customer Care":"Care — triages tickets, pulls order + refund eligibility, drafts replies.",
  "Live Selling":"Anchor — schedules lives, tracks viewers / GMV / CTOR, coaches hosts.",
  Warehouse:"Logi — stock cover, dispatch SLA, returns. Drafts restocks, flags QC risk.",
  Reporting:"Herald — daily / weekly / monthly client reports in plain English. Human approves.",
  Leads:"Prospector — sources qualified brand and partner leads across platforms daily.",
  Governance:"Sentinel — guards money, people and deletion. Routes consequential acts to the gate.",
  Memory:"Recall — stores your edits and decisions so the next draft starts closer to right.",
  Knowledge:"RAG · 538 chunks — grounded retrieval. Cites its source or says it does not know.",
  Calendar:"Notetaker — transcribes calls, pulls action items, drafts invites → your gate.",
};

const THREE_URLS=["https://cdn.jsdelivr.net/npm/three@0.128.0/build/three.min.js","https://unpkg.com/three@0.128.0/build/three.min.js"];
export function loadTonyThree():Promise<any>{
  const w=window as Window&{THREE?:any;__tonyThree?:Promise<any>};
  if(w.THREE)return Promise.resolve(w.THREE); if(w.__tonyThree)return w.__tonyThree;
  w.__tonyThree=new Promise((resolve,reject)=>{let i=0;const next=()=>{if(i>=THREE_URLS.length)return reject(new Error("Three.js unavailable"));const s=document.createElement("script");s.src=THREE_URLS[i++];s.async=true;s.onload=()=>w.THREE?resolve(w.THREE):next();s.onerror=()=>{s.remove();next()};document.head.appendChild(s)};next()});return w.__tonyThree;
}

export function mountTonyNorthStar(host:HTMLDivElement,initial:TonyVisualState):OrbitApi{
  const T=(window as Window&{THREE?:any}).THREE;if(!T)throw new Error("Three.js unavailable");
  const SUN=1.75,BASE=5.6,GAP=2.9,PER=5;let ringCount=0;const bodies:any[]=[];
  for(let i=0;i<NODES.length;i+=PER){const group=NODES.slice(i,i+PER),ri=ringCount++,a=BASE+ri*GAP,b=a*(1-(.018+ri*.01)),tilt=(ri%2?-1:1)*(3+ri*2.2)*Math.PI/180,speed=.075/(ri*.8+1.3);group.forEach((n,j)=>bodies.push({name:n[0],sub:n[1],color:n[2],kind:n[3],r:n[4],hasRing:n[5],a,b,tilt,speed,angle:j/group.length*Math.PI*2+ri*.4,ri}))}
  const OUTER=BASE+(ringCount-1)*GAP,scene=new T.Scene(),camera=new T.PerspectiveCamera(46,1.6,.5,900),renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"});
  renderer.setClearColor(0x000000,0);renderer.setPixelRatio(Math.min(devicePixelRatio||1,2.2));if(T.sRGBEncoding)renderer.outputEncoding=T.sRGBEncoding;if(T.ACESFilmicToneMapping)renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.domElement.className="tonyWebgl";host.appendChild(renderer.domElement);
  const labels=document.createElement("div");labels.className="tlabels";host.appendChild(labels);
  scene.add(new T.HemisphereLight(0x33406b,0x0b1020,.62));const sunLight=new T.PointLight(0xfff0cf,1.55,0,0);scene.add(sunLight);const fill=new T.DirectionalLight(0x6f8fc9,.32);fill.position.set(-8,10,-6);scene.add(fill);

  const rng=(seed:number)=>()=>{seed=(seed+0x6D2B79F5)|0;let x=seed;x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296};
  function galaxy(){const c=document.createElement("canvas");c.width=1536;c.height=768;const x=c.getContext("2d")!,r=rng(6001);x.fillStyle="#010306";x.fillRect(0,0,c.width,c.height);const grad=x.createRadialGradient(c.width*.34,c.height*.51,10,c.width*.34,c.height*.51,c.width*.8);grad.addColorStop(0,"rgba(145,92,68,.24)");grad.addColorStop(.25,"rgba(75,55,92,.16)");grad.addColorStop(.7,"rgba(10,31,54,.08)");grad.addColorStop(1,"rgba(0,0,0,0)");x.fillStyle=grad;x.fillRect(0,0,c.width,c.height);for(let i=0;i<3200;i++){const xx=r()*c.width,yy=c.height*.5+(r()+r()+r()-1.5)*c.height*.22,a=.14+r()*.62,rad=r()<.02?1.5:.25+r()*.8;x.beginPath();x.fillStyle=r()<.24?`rgba(255,226,196,${a})`:`rgba(198,222,255,${a})`;x.arc(xx,yy,rad,0,Math.PI*2);x.fill()}const t=new T.CanvasTexture(c);t.needsUpdate=true;return t}
  const sky=new T.Mesh(new T.SphereGeometry(400,64,48),new T.MeshBasicMaterial({map:galaxy(),side:T.BackSide,depthWrite:false,depthTest:false}));sky.rotation.z=.46;sky.rotation.x=.22;sky.renderOrder=-1;scene.add(sky);
  function stars(count:number,min:number,max:number,size:number,op:number){const p=new Float32Array(count*3),c=new Float32Array(count*3);for(let i=0;i<count;i++){const r=min+Math.random()*(max-min),th=Math.random()*Math.PI*2,ph=Math.acos(2*Math.random()-1);p[i*3]=r*Math.sin(ph)*Math.cos(th);p[i*3+1]=r*Math.cos(ph);p[i*3+2]=r*Math.sin(ph)*Math.sin(th);const warm=Math.random()<.09;c[i*3]=warm?1:.82;c[i*3+1]=warm?.9:.9;c[i*3+2]=warm?.78:1}const g=new T.BufferGeometry();g.setAttribute("position",new T.BufferAttribute(p,3));g.setAttribute("color",new T.BufferAttribute(c,3));const o=new T.Points(g,new T.PointsMaterial({size,sizeAttenuation:true,vertexColors:true,transparent:true,opacity:op,depthWrite:false}));scene.add(o);return o}const starsNear=stars(420,40,80,.115,.5);stars(700,80,150,.085,.3);
  const astN=1850,astP=new Float32Array(astN*3);for(let i=0;i<astN;i++){const r=7.2+Math.random()*5+(Math.random()-.5)*.7,a=Math.random()*Math.PI*2;astP[i*3]=Math.cos(a)*r;astP[i*3+1]=(Math.random()-.5)*.55;astP[i*3+2]=Math.sin(a)*r}const ag=new T.BufferGeometry();ag.setAttribute("position",new T.BufferAttribute(astP,3));const ast=new T.Points(ag,new T.PointsMaterial({color:0xaab3bd,size:.045,sizeAttenuation:true,transparent:true,opacity:.54,depthWrite:false}));ast.rotation.x=-.08;scene.add(ast);

  function glowTex(color:number){const c=document.createElement("canvas");c.width=c.height=256;const x=c.getContext("2d")!,rr=(color>>16)&255,gg=(color>>8)&255,bb=color&255,g=x.createRadialGradient(128,128,2,128,128,128);g.addColorStop(0,"rgba(255,255,255,.98)");g.addColorStop(.08,`rgb(${rr},${gg},${bb})`);g.addColorStop(.62,`rgba(${rr},${gg},${bb},.26)`);g.addColorStop(1,`rgba(${rr},${gg},${bb},0)`);x.fillStyle=g;x.fillRect(0,0,256,256);const t=new T.CanvasTexture(c);t.needsUpdate=true;return t}
  const sunUniforms={t:{value:0},cDeep:{value:new T.Color(0xc85a12)},cMid:{value:new T.Color(0xffab33)},cHot:{value:new T.Color(0xfff6dc)},pulse:{value:1}};
  const sunMat=new T.ShaderMaterial({uniforms:sunUniforms,vertexShader:"varying vec3 vPos;varying vec3 vN;varying vec3 vV;void main(){vPos=position;vN=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.);vV=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}",fragmentShader:"uniform float t;uniform vec3 cDeep,cMid,cHot;uniform float pulse;varying vec3 vPos,vN,vV;float h(vec3 p){p=fract(p*.3183099+vec3(.71,.113,.419));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}float n(vec3 x){vec3 i=floor(x),f=fract(x);f=f*f*(3.-2.*f);return mix(mix(mix(h(i),h(i+vec3(1,0,0)),f.x),mix(h(i+vec3(0,1,0)),h(i+vec3(1,1,0)),f.x),f.y),mix(mix(h(i+vec3(0,0,1)),h(i+vec3(1,0,1)),f.x),mix(h(i+vec3(0,1,1)),h(i+vec3(1,1,1)),f.x),f.y),f.z);}float f(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*n(p);p=p*2.03+vec3(1.7,9.2,4.3);a*=.5;}return v;}void main(){vec3 p=normalize(vPos);float g=mix(f(p*3.4+vec3(0,t*.04,0)),f(p*8.-vec3(t*.028,0,t*.018)),.45),mu=max(dot(normalize(vN),normalize(vV)),0.),limb=pow(mu,.42);vec3 col=mix(cDeep,cMid,smoothstep(.28,.58,g));col=mix(col,cHot,smoothstep(.58,.88,g));col*=mix(.58,1.32,limb)*pulse;col+=cHot*pow(smoothstep(.82,.98,g),2.)*.55;gl_FragColor=vec4(col,1.);}"});
  const sun=new T.Mesh(new T.SphereGeometry(SUN,64,64),sunMat);scene.add(sun);const bloomTex=glowTex(0xffffff),blooms=[3.6,.6,6.8,.28,12,.11].reduce((a:any[],_,i,arr)=>{if(i%2)return a;const m=new T.SpriteMaterial({map:bloomTex,transparent:true,opacity:arr[i+1],blending:T.AdditiveBlending,depthWrite:false,color:0xffc266}),sp=new T.Sprite(m);sp.scale.set(SUN*arr[i],SUN*arr[i],1);scene.add(sp);a.push(sp);return a},[]);

  function planetTex(kind:string,color:number,seed:number){const W=256,H=128,c=document.createElement("canvas");c.width=W;c.height=H;const x=c.getContext("2d")!,im=x.createImageData(W,H),d=im.data,r=rng(seed),br=(color>>16)&255,bg=(color>>8)&255,bb=color&255,bands=["jovian","venusian","icegiant","uranian"].includes(kind);for(let y=0;y<H;y++)for(let xx=0;xx<W;xx++){const i=(y*W+xx)*4,u=xx/W,v=y/H,n=(Math.sin(u*31+Math.sin(v*17+seed)*2)+Math.sin(v*67+u*9)+Math.sin((u+v)*111))*.115+(r()-.5)*.14;let q=bands?Math.sin(v*Math.PI*(kind==="jovian"?18:10)+Math.sin(u*9)*.35)*.22+n:n;if(kind==="lava")q+=Math.abs(Math.sin(u*37+v*23))*.32;if(kind==="carbon")q-=.28;const sh=Math.max(.18,Math.min(1.3,.68+q));let R=br*sh,G=bg*sh,B=bb*sh;if(kind==="terran"||kind==="ocean"){const land=Math.sin(u*14+Math.sin(v*10)*2)+Math.sin(v*21-u*5);if(land>.45){R=52+80*sh;G=92+85*sh;B=42+35*sh}else{R=12+15*sh;G=43+45*sh;B=86+70*sh}}if(kind==="jovian"){R=150+80*sh;G=94+70*sh;B=48+35*sh}if(kind==="lava"){const hot=Math.abs(Math.sin(u*29+v*31));R=80+175*hot;G=20+105*hot;B=24+25*sh}d[i]=Math.min(255,R);d[i+1]=Math.min(255,G);d[i+2]=Math.min(255,B);d[i+3]=255}x.putImageData(im,0,0);const t=new T.CanvasTexture(c);t.wrapS=T.RepeatWrapping;t.needsUpdate=true;return t}
  const pivots=new Map<number,any>();bodies.forEach((n,idx)=>{if(!pivots.has(n.ri)){const p=new T.Group();p.rotation.x=n.tilt;scene.add(p);pivots.set(n.ri,p);const pts=[];for(let j=0;j<96;j++){const th=j/96*Math.PI*2;pts.push(new T.Vector3(Math.cos(th)*n.a,0,Math.sin(th)*n.b))}p.add(new T.LineLoop(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:0x6f80b0,transparent:true,opacity:.15,depthWrite:false})))}const holder=new T.Group();pivots.get(n.ri).add(holder);const props:any={map:planetTex(n.kind,n.color,idx*77+13),roughness:.82,metalness:.03};if(n.kind==="lava"){props.emissive=new T.Color(0x8b1308);props.emissiveIntensity=.55}const mesh=new T.Mesh(new T.SphereGeometry(n.r,40,40),new T.MeshStandardMaterial(props));holder.add(mesh);if(n.hasRing){const ring=new T.Mesh(new T.RingGeometry(n.r*1.28,n.r*2.15,72),new T.MeshBasicMaterial({color:n.color,transparent:true,opacity:.36,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=n.kind==="uranian"?.12:Math.PI/2.35;ring.rotation.y=n.kind==="uranian"?.35:0;holder.add(ring)}Object.assign(n,{holder,mesh,spin:.18+Math.random()*.22})});

  const labelRecs:any[]=[];function label(obj:any,name:string,sub:string,core=false,node:any=null){const e=document.createElement("div");e.className="tlabel"+(core?" core":"");e.innerHTML=core?`<div class=\"tn\">${name}</div>`:`<div class=\"tn\">${name}</div><div class=\"ts\">${sub}</div>`;labels.appendChild(e);labelRecs.push({obj,e,core,node,r:node?.r||SUN})}label(sun,"TONY","",true);bodies.forEach(n=>label(n.mesh,n.name,n.sub,false,n));
  const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));let theta=.42,phi=1.24,fitR=22,camR=22,userZoom=false,drag=false,lastX=0,lastY=0,moved=false,hover:any=null,selected:any=null,dead=false,raf=0,state=initial;const focus=new T.Vector3(),zero=new T.Vector3(),world=new T.Vector3(),proj=new T.Vector3(),mouse=new T.Vector2(),ray=new T.Raycaster(),clock=new T.Clock();
  function needed(){const w=host.clientWidth||800,h=host.clientHeight||500,asp=Math.max(.55,w/h),q=Math.tan(camera.fov*Math.PI/360),v=OUTER*Math.abs(Math.cos(phi))+OUTER*.2*Math.abs(Math.sin(phi))+1.5;return clamp(Math.max((OUTER+1.4)/(q*asp),v/q)*1.05,12,44)}function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);fitR=needed();if(!userZoom)camR=fitR}const ro=new ResizeObserver(resize);ro.observe(host);resize();
  function pick(e:PointerEvent){const r=host.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(bodies.map(n=>n.mesh),false)[0];return hit?bodies.find(n=>n.mesh===hit.object):null}function rec(n:any){return labelRecs.find(x=>x.node===n)}function setHover(n:any){if(hover===n)return;if(hover)rec(hover)?.e.classList.remove("hov");hover=n;if(hover)rec(hover)?.e.classList.add("hov");host.style.cursor=hover?"pointer":drag?"grabbing":"grab"}function select(n:any){if(selected)rec(selected)?.e.classList.remove("sel");selected=selected===n?null:n;if(selected)rec(selected)?.e.classList.add("sel");host.dispatchEvent(new CustomEvent("tony-node",{detail:selected?{name:selected.name,sub:selected.sub,description:DESC[selected.name]||""}:null}))}
  host.addEventListener("pointerdown",e=>{drag=true;moved=false;lastX=e.clientX;lastY=e.clientY;host.setPointerCapture?.(e.pointerId)});host.addEventListener("pointermove",e=>{if(!drag){setHover(pick(e));return}const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;lastX=e.clientX;lastY=e.clientY;theta-=dx*.005;phi=clamp(phi+dy*.004,.48,2.30)});host.addEventListener("pointerup",e=>{if(!moved){const n=pick(e);if(n)select(n);else if(selected)select(selected)}drag=false});host.addEventListener("pointerleave",()=>{if(!drag)setHover(null)});host.addEventListener("wheel",e=>{e.preventDefault();userZoom=true;const d=selected?clamp(needed()*.42,7.5,16):needed();camR=clamp(camR+(e.deltaY>0?1.25:-1.25),d*.42,d*1.9)},{passive:false});
  function labelsUpdate(){const w=host.clientWidth,h=host.clientHeight;labelRecs.forEach(r=>{r.obj.getWorldPosition(world);proj.copy(world).project(camera);const x=(proj.x*.5+.5)*w,y=(-proj.y*.5+.5)*h;r.e.style.transform=`translate(-50%,0) translate(${x}px,${y+(r.core?SUN*13:r.r*28)}px)`;r.e.style.opacity=proj.z>-1&&proj.z<1?"1":"0"})}
  function setState(s:TonyVisualState){state=s;const c=new T.Color({idle:0xffb347,listening:0x8ec6ff,thinking:0xc9a6ff,speaking:0xffd166}[s]);blooms.forEach((b:any)=>b.material.color.copy(c))}setState(initial);
  function tick(){if(dead)return;const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;sunUniforms.t.value+=dt;sunUniforms.pulse.value=1+.025*Math.sin(t*1.7)+(state==="speaking"?.045*Math.sin(t*8.5):0);sun.rotation.y+=dt*.025;ast.rotation.y+=dt*.0035;bodies.forEach(n=>{n.angle+=dt*n.speed;n.holder.position.set(Math.cos(n.angle)*n.a,0,Math.sin(n.angle)*n.b);n.mesh.rotation.y+=dt*n.spin});if(!drag&&!selected)theta+=dt*.035;fitR=needed();const desired=selected?clamp(fitR*.42,7.5,16):fitR;if(!userZoom)camR+=(desired-camR)*Math.min(1,dt*2.2);if(selected){selected.holder.getWorldPosition(world);focus.lerp(world,Math.min(1,dt*3))}else focus.lerp(zero,Math.min(1,dt*3));const x=camR*Math.sin(phi)*Math.sin(theta),z=camR*Math.sin(phi)*Math.cos(theta),y=camR*Math.cos(phi);camera.position.set(focus.x+x,focus.y+y,focus.z+z);camera.lookAt(focus);sky.position.copy(camera.position);starsNear.material.opacity=clamp(.36+.12*Math.sin(t*.5)+(state==="speaking"?.12*Math.abs(Math.sin(t*9.4)):0),.08,1);renderer.render(scene,camera);labelsUpdate();if(selected){selected.mesh.getWorldPosition(world);proj.copy(world).project(camera);host.style.setProperty("--fx",`${(proj.x*.5+.5)*100}%`);host.style.setProperty("--fy",`${(-proj.y*.5+.5)*100}%`)}raf=requestAnimationFrame(tick)}tick();
  return{setState,zoom:(dir:number)=>{userZoom=true;const d=selected?clamp(needed()*.42,7.5,16):needed();camR=clamp(camR+dir*2.4,d*.42,d*1.9)},reset:()=>{userZoom=false;theta=.42;phi=1.24;camR=fitR;setHover(null);if(selected)select(selected)},destroy:()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect();try{scene.traverse((o:any)=>{o.geometry?.dispose?.();const ms=o.material?(Array.isArray(o.material)?o.material:[o.material]):[];ms.forEach((m:any)=>{m.map?.dispose?.();m.dispose?.()})});renderer.dispose()}catch{}labels.remove();renderer.domElement.remove()}};
}
