"use client";

import Link from "next/link";
import "./tony-startup.css";
import { useEffect, useRef, useState } from "react";
import { openAssistantStream } from "@/lib/assistant/client-stream";
import { useTonyVoice } from "@/lib/voice/useTonyVoice";
import { TonyPersonalityDial } from "./TonyPersonalityDial";
import { watchOrbitReadiness } from "@/lib/tony/orbit-readiness";
import { type ToneSettings } from "@/lib/assistant/tone";
type TonyVisualState = "idle" | "listening" | "thinking" | "speaking";

// srcDoc keeps this visual document isolated without weakening the app's frame-denial headers.
const ORBIT_DOCUMENT="<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Tony cognition orbit</title><link rel=\"stylesheet\" href=\"/tony/orbit.css\"></head><body><div class=\"tstage\" id=\"tstage\"><div id=\"tmeta\"></div><div id=\"orbcap\"></div><div class=\"tvignette\"></div></div><script src=\"/tony/three-r128.min.js\"></script><script src=\"/tony/orbit.js\"></script><script src=\"/tony/planet-menu.js\"></script></body></html>";

type Speaker="you"|"ai";
type Line={id:number;speaker:Speaker;text:string};
export type TonyInitialMessage={role:"user"|"assistant";content:string};
const NAV=[["Command center","/"],["Tony","/assistant"],["Text chat","/assistant?view=chat"],["Tony controls","/tony"],["Tasks","/tasks"],["People","/people"],["Metrics","/metrics"],["Daily Tap","/daily-tap"],["Updates","/updates"],["Warehouse","/warehouse/overview"],["Creative","/creative-studio"],["Reports","/reports"]] as const;

export function TonyNorthStarPage({initialConversationId=null,initialMessages=[],orgId,userId,tone}:{initialConversationId?:string|null;initialMessages?:TonyInitialMessage[];orgId:string;userId:string;tone:ToneSettings}){
  const conversation=useRef<string|null>(initialConversationId),voice=useTonyVoice(conversation),frameRef=useRef<HTMLIFrameElement|null>(null),abortRef=useRef<AbortController|null>(null),transcriptRef=useRef<HTMLDivElement|null>(null),followRef=useRef(true),nextId=useRef(initialMessages.length+1),seenQ=useRef(""),seenA=useRef("");
  const [input,setInput]=useState(""),[busy,setBusy]=useState(false),[tier,setTier]=useState(""),[drawer,setDrawer]=useState(false),[tool,setTool]=useState<"trace"|"loop"|"memory"|null>(null),[personality,setPersonality]=useState(false),[orbitError,setOrbitError]=useState(false),[lines,setLines]=useState<Line[]>(()=>initialMessages.map((m,i)=>({id:i+1,speaker:m.role==="assistant"?"ai":"you",text:m.content})));
  const thinking=busy||voice.state==="thinking"||voice.state==="transcribing";
  const [orbitLoading, setOrbitLoading] = useState(true);
  const [orbitAttempt, setOrbitAttempt] = useState(0);
  const [orbitMounted, setOrbitMounted] = useState(false);
  useEffect(() => { setOrbitMounted(true); }, []);
  const visual:TonyVisualState=thinking?"thinking":voice.state==="speaking"?"speaking":voice.state==="capturing"?"listening":"idle";
  const status=thinking?`thinking${tier?` · ${tier}`:""}`:voice.state==="speaking"?"speaking · Tony":voice.state==="capturing"?"listening · You":"ready · Tony";

  function orbit(action:string,extra:Record<string,unknown>={}){frameRef.current?.contentWindow?.postMessage({source:"tony-host",action,...extra},window.location.origin)}
  useEffect(()=>{orbit("state",{state:visual})},[visual]);
  useEffect(() => watchOrbitReadiness({hostWindow: window,getFrameWindow: () => frameRef.current?.contentWindow ?? null,onSettled: (ready) => { setOrbitError(!ready); setOrbitLoading(false); },}), [orbitAttempt]);
  useEffect(() => () => { abortRef.current?.abort(); }, []);
  function retryOrbit(){setOrbitLoading(true);setOrbitError(false);setOrbitAttempt(attempt=>attempt+1)}
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){setDrawer(false);setTool(null);setPersonality(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  useEffect(()=>{const el=transcriptRef.current;if(el&&followRef.current)el.scrollTop=el.scrollHeight},[lines]);
  useEffect(()=>{if(voice.state==="capturing"){seenQ.current="";seenA.current=""}},[voice.state]);
  useEffect(()=>{if(voice.lastTranscript&&voice.lastTranscript!==seenQ.current){seenQ.current=voice.lastTranscript;setLines(p=>[...p,{id:nextId.current++,speaker:"you",text:voice.lastTranscript}])}},[voice.lastTranscript]);
  useEffect(()=>{if(voice.lastReply&&voice.lastReply!==seenA.current){seenA.current=voice.lastReply;setLines(p=>[...p,{id:nextId.current++,speaker:"ai",text:voice.lastReply}])}},[voice.lastReply]);

  async function ask(){const message=input.trim();if(!message||busy||!["idle","error"].includes(voice.state))return;followRef.current=true;setInput("");setBusy(true);const uid=nextId.current++,aid=nextId.current++;setLines(p=>[...p,{id:uid,speaker:"you",text:message},{id:aid,speaker:"ai",text:""}]);try{const controller=new AbortController();abortRef.current=controller;const result=await openAssistantStream({conversationId:conversation.current,message},controller.signal);if(result.kind==="json"){const error=typeof result.data.error==="string"?result.data.error:"Tony is temporarily unavailable.";setLines(p=>p.map(l=>l.id===aid?{...l,text:error}:l));return}let answer="";for await(const event of result.events){if(event.type==="meta"){if(event.conversationId)conversation.current=event.conversationId;if(event.tier)setTier(event.tier.toLowerCase())}else if(event.type==="delta"){answer+=event.text;setLines(p=>p.map(l=>l.id===aid?{...l,text:answer}:l))}else if(event.type==="error"){answer=event.error;setLines(p=>p.map(l=>l.id===aid?{...l,text:answer}:l))}}if(!answer)setLines(p=>p.map(l=>l.id===aid?{...l,text:"I could not produce a grounded answer for that ask."}:l))}catch{setLines(p=>p.map(l=>l.id===aid?{...l,text:"Tony is temporarily unavailable."}:l))}finally{setBusy(false)}}

  return <>
    {orbitLoading && <div className="arrivalStatus" role="status">TONY · INITIALIZING</div>}
    <main className={`tonyNS${orbitLoading ? " arriving" : ""}`} aria-busy={orbitLoading} ref={element => {if(element)element.inert=orbitLoading}}>
    <section className="tstage" aria-label="Tony cognition solar system">{orbitMounted && <iframe key={orbitAttempt} ref={frameRef} srcDoc={ORBIT_DOCUMENT} title="Tony solar system" className="orbitFrame" onLoad={()=>{orbit("state",{state:visual});orbit("ready")}} />}
      <div className="tcapDim" aria-hidden/>
      {lines.length>0&&<div className="tcapBehind"><div className="transcript" ref={transcriptRef} onScroll={e=>{const el=e.currentTarget;followRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<40}} role="log" aria-label="Conversation with Tony">{lines.map(l=><div key={l.id} className={`trow ${l.speaker}`}><span className="spk">{l.speaker==="ai"?"Tony":"You"}</span><span className="copy">{l.text||"Thinking…"}</span></div>)}</div></div>}
      {orbitError&&<div className="fallback"><div role="alert"><p>Tony&apos;s space view could not start. You can still use chat.</p><button type="button" onClick={retryOrbit}>Retry space view</button></div></div>}
      <div className="tvignette" aria-hidden/>
    </section>

    <button className="tfToggle" type="button" onClick={()=>setDrawer(true)} title="Menu">☰</button>
    <div className="tfIcons"><button type="button" onClick={()=>setTool("trace")} title="Reasoning trace">🧭</button><button type="button" onClick={()=>setTool("loop")} title="Cognition loop">♻️</button><button type="button" onClick={()=>setTool("memory")} title="Memory & continuous learning">📚</button><div className="personality"><button type="button" onClick={()=>setPersonality(v=>!v)} title="Personality">🎚</button>{personality&&<div className="hang"><h3>🎚 Personality</h3><TonyPersonalityDial orgId={orgId} userId={userId} settings={tone}/></div>}</div></div>

    <section className="tfDock"><div className={`orbstate ${visual}`}>✣ &nbsp;{status}</div><div className="mic"><input aria-label="Message Tony" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void ask()}}} placeholder="Ask Tony... e.g. what should I do about FML today?" disabled={busy||!["idle","error"].includes(voice.state)}/><button type="button" aria-label={voice.state==="capturing"?"Stop recording":"Talk to Tony"} className={voice.state==="capturing"?"rec":""} disabled={busy||(voice.state!=="capturing"&&!voice.pushToTalkReady)} onClick={voice.state==="capturing"?voice.stopTalking:voice.talk}>🎙</button><button type="button" aria-label="Send message" disabled={busy||!input.trim()||!["idle","error"].includes(voice.state)} onClick={()=>void ask()}>↑</button></div>{voice.error&&<p role="alert">{voice.error}</p>}{voice.state==="speaking"&&<button type="button" onClick={voice.stopSpeaking}>Stop speaking</button>}<div className="route"><span className={tier.includes("haiku")?"on":""}>Claude Haiku · fast</span><span className={tier.includes("opus")?"on opus":""}>Claude Opus · deep</span><span>OpenAI · RAG/voice</span></div><div className="costtick">{tier?`Model: ${tier}`:"Ready for your message"}</div></section>
    <div className="thint">DRAG TO ORBIT · HOVER A PLANET · CLICK TO PIN · SCROLL TO ZOOM</div><div className="tzoom"><button aria-label="Zoom in" onClick={()=>orbit("zoom",{direction:-1})}>+</button><button aria-label="Zoom out" onClick={()=>orbit("zoom",{direction:1})}>−</button><button aria-label="Reset orbit" onClick={()=>orbit("reset")}>↻</button></div>

    {drawer&&<><button className="backdrop" onClick={()=>setDrawer(false)} aria-label="Close navigation"/><aside className="drawer"><div className="brand"><div className="logo">M</div><div><b>M-THRYVE OS</b><small>MThryve workspace</small></div></div><div className="nlabel">Agentic Layer</div><nav>{NAV.map(([label,href])=><Link key={href} href={href} className={href==="/tony"?"on":""} onClick={()=>setDrawer(false)}>{label}</Link>)}</nav></aside></>}
    {tool&&<div className="modalBack" onClick={()=>setTool(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setTool(null)}>✕</button>{tool==="trace"&&<><h3>🧭 How Tony works</h3><div className="trace"><div><b>01</b> Ground the ask in workspace data + RAG.</div><div><b>02</b> Route to the responsible agent.</div><div><b>03</b> Compare evidence, constraints and recent memory.</div><div><b>04</b> Draft the action; consequential acts go to Review Gate.</div></div></>}{tool==="loop"&&<><h3>♻️ Cognition loop</h3><Link href="/tony">Open live cognition controls →</Link><div className="blocks"><div><b>Observe</b><span>Signals, tasks, conversations, metrics</span></div><div><b>Retrieve</b><span>Knowledge + decisions + recent context</span></div><div><b>Reason</b><span>Agent plan with grounded evidence</span></div><div><b>Act / Gate</b><span>Safe automation; consequential work for approval</span></div></div></>}{tool==="memory"&&<><h3>📚 Memory & continuous learning</h3><Link href="/tony">Open saved memories →</Link><div className="blocks"><div><b>Operator preferences</b><span>Your edits and approvals tune the next draft.</span></div><div><b>Company knowledge</b><span>Workspace knowledge is retrieved by the assistant backend.</span></div><div><b>Decision trail</b><span>Approved actions become reusable operating context.</span></div></div></>}</div></div>}

    <style jsx>{`
      .tonyNS{--line:#1e2a35;--ink:#e9f0f6;--mut:#8b9aa8;--teal:#2dd4bf;--purp:#a78bfa;position:fixed;inset:0;overflow:hidden;background:radial-gradient(ellipse at 50% 40%,#171238 0%,#0c0a22 44%,#050510 100%);color:var(--ink);font-family:Rajdhani,ui-sans-serif,system-ui,sans-serif;isolation:isolate}
      .orbitFrame{position:absolute;inset:0;width:100%;height:100%;border:0}.tstage{position:absolute;inset:0;z-index:1;overflow:hidden;background:radial-gradient(ellipse at 50% 46%,#04080f 0%,#020409 50%,#000103 100%);cursor:grab;touch-action:none;user-select:none}.tstage:active{cursor:grabbing}.tvignette{position:absolute;inset:0;z-index:3;pointer-events:none;background:radial-gradient(ellipse at 50% 50%,transparent 38%,rgba(2,4,9,.46) 72%,rgba(1,2,5,.88) 100%)}
      .tcapDim{position:absolute;left:50%;bottom:64px;transform:translateX(-50%);z-index:0;width:min(660px,94%);height:184px}.tcapBehind{position:absolute;left:50%;bottom:175px;transform:translateX(-50%);z-index:7;width:min(620px,90%);pointer-events:auto}.transcript{max-height:24vh;overflow:auto}.trow{display:flex;min-height:28px;align-items:center;padding:1px 6px;gap:7px}.trow.ai{justify-content:flex-start}.trow.you{justify-content:flex-end}.spk{font:800 8px/1 ui-monospace,monospace;color:#f5b942}.you .spk{color:#5aa9e6}.copy{max-width:80%;overflow-wrap:anywhere;white-space:pre-wrap;font-size:14px;line-height:1.5}
      .tfToggle{position:absolute;top:18px;left:18px;z-index:60;width:42px;height:42px;border-radius:12px;background:rgba(13,20,27,.85);border:1px solid var(--line);color:var(--ink);cursor:pointer}.tfIcons{position:absolute;top:18px;right:18px;z-index:60;display:flex;flex-direction:column;gap:10px}.tfIcons>button,.personality>button{width:42px;height:42px;border-radius:12px;background:rgba(13,20,27,.85);border:1px solid var(--line);color:var(--ink);cursor:pointer}.personality{position:relative}.hang{position:absolute;top:0;right:52px;width:260px;background:#111820;border:1px solid var(--purp);border-radius:12px;padding:14px}
      .tfDock{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);z-index:55;display:flex;flex-direction:column;align-items:center;gap:9px;width:min(560px,92%);pointer-events:none}.tfDock>button,.orbstate,.mic,.route{pointer-events:auto}.orbstate{font-size:12px;font-weight:800;padding:5px 12px;border:1px solid #2b2a4d;border-radius:20px;background:rgba(7,9,25,.83);color:#70d8d0}.mic{width:100%;display:flex;align-items:center;gap:9px;background:rgba(13,20,27,.94);border:1px solid var(--line);border-radius:24px;padding:7px 8px 7px 14px}.mic input{flex:1;background:transparent;border:0;outline:0;color:var(--ink);font-size:16px;min-width:0}.mic button{width:34px;height:34px;border:0;border-radius:50%;background:linear-gradient(135deg,var(--purp),var(--teal));cursor:pointer}.route{display:flex;gap:6px;justify-content:center}.route span{font-size:10px;padding:3px 9px;border:1px solid var(--line);border-radius:20px;color:var(--mut)}.costtick{font-size:10px;color:var(--mut)}.thint{position:absolute;left:50%;bottom:4px;transform:translateX(-50%);z-index:54;font:700 8.5px/1 ui-monospace,monospace;color:#526e89}.tzoom{position:absolute;right:18px;bottom:12px;z-index:60;display:flex;gap:5px}.tzoom button{width:26px;height:26px;border-radius:7px;border:1px solid #2b2a4d;background:rgba(10,9,32,.72);color:#aab0d4}
      .backdrop{position:absolute;inset:0;z-index:80;border:0;background:rgba(0,0,0,.58)}.drawer{position:absolute;z-index:90;top:16px;bottom:16px;left:16px;width:min(300px,calc(100vw - 32px));padding:14px;background:#0d141b;border:1px solid rgba(45,212,191,.18);border-radius:18px;overflow:auto}.brand{display:flex;gap:11px;align-items:center}.logo{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,var(--teal),#3ecf8e);display:grid;place-items:center;color:#04120c}.nlabel{font-size:9px;color:#6f8395;margin:18px 10px 7px}.drawer nav{display:flex;flex-direction:column;gap:4px}.drawer nav a{padding:9px 11px;border-radius:10px;color:#9cabb8;text-decoration:none}.modalBack{position:absolute;inset:0;z-index:100;display:grid;place-items:center;background:rgba(0,0,0,.65)}.modal{position:relative;width:min(480px,92vw);background:#111820;border:1px solid var(--line);border-radius:14px;padding:20px}.close{position:absolute;top:10px;right:10px}.trace,.blocks{display:grid;gap:8px}.blocks>div{display:grid;grid-template-columns:90px 1fr;gap:10px;padding:10px;border:1px solid var(--line);border-radius:9px}.fallback{position:absolute;inset:0;z-index:10;display:grid;place-items:center;color:var(--mut)}
      @media(max-width:820px){.tfDock{width:calc(100vw - 32px)}.route,.costtick,.thint{display:none}}
    `}</style>
  </main></>
}
