"use client";
// components/content-studio/ContentStudioClient.tsx
// M1 — the interactive Content Studio: pick a content type, fill the brief, generate.
import { useMemo, useState } from "react";
import { TEMPLATES } from "@/lib/content/templates";

export function ContentStudioClient() {
  const [templateKey, setTemplateKey] = useState(TEMPLATES[0]?.key ?? "");
  const [inputs, setInputs] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [output, setOutput] = useState("");
  const [model, setModel] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const tpl = useMemo(() => TEMPLATES.find((t) => t.key === templateKey), [templateKey]);

  async function generate() {
    setLoading(true); setError(""); setOutput(""); setCopied(false);
    try {
      const res = await fetch("/api/content-studio/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ templateKey, inputs }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      setOutput(data.output); setModel(data.model);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      {/* Brief */}
      <section className="rounded-lg border border-charcoal-700 bg-charcoal-900 p-5">
        <label className="mb-2 block text-sm font-semibold text-ink">Content type</label>
        <select
          className="mb-4 w-full rounded-md border border-charcoal-700 bg-charcoal-950 p-2.5 text-sm text-ink"
          value={templateKey}
          onChange={(e) => { setTemplateKey(e.target.value); setInputs({}); setOutput(""); }}
        >
          {TEMPLATES.map((t) => (
            <option key={t.key} value={t.key}>{t.label} · {t.department}</option>
          ))}
        </select>
        {tpl && <p className="mb-4 text-xs text-ink-muted">{tpl.description}</p>}

        {tpl?.fields.map((f) => (
          <div key={f.name} className="mb-3">
            <label className="mb-1 block text-xs text-ink-muted">{f.label}</label>
            {f.type === "textarea" ? (
              <textarea
                className="min-h-[80px] w-full rounded-md border border-charcoal-700 bg-charcoal-950 p-2.5 text-sm text-ink"
                placeholder={f.placeholder}
                value={inputs[f.name] ?? ""}
                onChange={(e) => setInputs({ ...inputs, [f.name]: e.target.value })}
              />
            ) : f.type === "select" ? (
              <select
                className="w-full rounded-md border border-charcoal-700 bg-charcoal-950 p-2.5 text-sm text-ink"
                value={inputs[f.name] ?? ""}
                onChange={(e) => setInputs({ ...inputs, [f.name]: e.target.value })}
              >
                <option value="">— None —</option>
                {(f.options ?? []).map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            ) : (
              <input
                className="w-full rounded-md border border-charcoal-700 bg-charcoal-950 p-2.5 text-sm text-ink"
                placeholder={f.placeholder}
                value={inputs[f.name] ?? ""}
                onChange={(e) => setInputs({ ...inputs, [f.name]: e.target.value })}
              />
            )}
          </div>
        ))}

        <button
          onClick={generate}
          disabled={loading}
          className="mt-2 w-full rounded-md bg-teal-500 py-2.5 text-sm font-semibold text-charcoal-950 hover:bg-teal-400 disabled:opacity-60"
        >
          {loading ? "Generating…" : "✦ Generate"}
        </button>
        {error && <p className="mt-3 text-xs text-red-400">{error}</p>}
      </section>

      {/* Output */}
      <section className="rounded-lg border border-charcoal-700 bg-charcoal-900 p-5">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-sm font-semibold text-ink">Result</h2>
          {output && (
            <button
              onClick={() => { navigator.clipboard.writeText(output); setCopied(true); }}
              className="text-xs text-teal-400 hover:text-teal-300"
            >
              {copied ? "Copied ✓" : "Copy"}
            </button>
          )}
        </div>
        {output ? (
          <>
            <pre className="whitespace-pre-wrap break-words font-sans text-sm text-ink">{output}</pre>
            {model && <p className="mt-4 font-mono text-[10px] uppercase tracking-wider text-ink-muted">generated by {model}</p>}
          </>
        ) : (
          <p className="text-sm text-ink-muted">Fill the brief and hit Generate — your content appears here.</p>
        )}
      </section>
    </div>
  );
}
